### ISSUE TITLE
How to create a table directly using the schema from an ibis dataframe?

### ISSUE THREAD

**Issue by stereoF** [ibis-project/ibis#8924]
### Discussed in https://github.com/ibis-project/ibis/discussions/8911

<div type='discussions-op-text'>

<sup>Originally posted by **stereoF** April  7, 2024</sup>
How to create a table directly using the schema from an ibis dataframe?

I've built a dataframe with ibis: df_play. I wanted to directly use df_play's schema to create a table in the database, but it failed:
`con2.create_table('algo_play', schema=df_play.schema())
`

Error message:
DatabaseError: HTTPDriver for http://cc-j6c9l15edn66o817k.public.clickhouse.ads.aliyuncs.com:8123/ returned response code 400) Code: 62. DB::Exception: Syntax error: failed at position 620 (end of query) (line 19, col 12): . Expected one of: token, Arrow, DoubleColon, non-empty parenthesized list of expressions, end of query. (SYNTAX_ERROR) (version 22.8.5.29)
</div>

**Comment by lostmygithubaccount** [comment]
hi @stereoF, apologies for missing the discussion earlier! what verion of Ibis are you using? this seems to work for me w/ the ClickHouse backend on main:

```python
[ins] In [1]: import ibis

[ins] In [2]: ibis.options.interactive = True

[ins] In [3]: con = ibis.clickhouse.connect()

[ins] In [4]: data = {"a": [1, 2, 3], "b": ["a", "b", "c"]}

[ins] In [5]: t = ibis.memtable(data)

[ins] In [6]: a = con.create_table("a", t)

[ins] In [7]: b = con.create_table("b", schema=t.schema())

[ins] In [8]: a
Out[8]:
┏━━━━━━━┳━━━━━━━━┓
┃ a     ┃ b      ┃
┡━━━━━━━╇━━━━━━━━┩
│ int64 │ string │
├───────┼────────┤
│     1 │ a      │
│     2 │ b      │
│     3 │ c      │
└───────┴────────┘

[ins] In [9]: b
Out[9]:
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ a                    ┃ b                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ int64                │ string               │
└──────────────────────┴──────────────────────┘
```

**Comment by stereoF** [comment]
Hi @lostmygithubaccount 
The version I used was 8.0.0

**Comment by stereoF** [comment]
@lostmygithubaccount Did I need to upgrade to a new version to solve this problem?

**Comment by lostmygithubaccount** [comment]
@stereoF yes upgrading should fix it. we have not released 9.0.0 yet (will be soon), you can directly install from main or a weekly prerelease (`pip install --upgrade --pre 'ibis-framework[<your-backend>]'`) for now if that works

**Comment by stereoF** [comment]
@gforsyth

**Comment by stereoF** [comment]
@gforsyth 

ibis.Schema {
  play_id                      !string
  uid                          !int64
  feat1             float64
  feat2              float64
  feat3    float64
  feat4         float64
  feat5                 float64
  feat6         float64
  feat7  float64
  feat8           float64
  feat9         float64
  feat10        float64
  feat11         float64
  play_timestamp               !int64
  tag_date                     !int32
}

**Comment by gforsyth** [comment]
Thanks @stereoF !  We've added a test to confirm that this works in the upcoming 9.0 release (any day now!)

**Comment by stereoF** [comment]
> Thanks @stereoF ! We've added a test to confirm that this works in the upcoming 9.0 release (any day now!)

Hi, I have upgrade to 9.0 release, but this problem still exist.
`ibis.__version__`
`'9.0.0'`

```
schema = ibis.schema(
    [
        ('user_id', 'int64'),
        ('account_id', 'string'),
        ('t_normal', 'float64'),
        ('t_sbl', 'float64'),
        ('t_mg', 'float64'),
        ('t_sbl_mg', 'float64'),
        ('t_sbl_mg_rich', 'float64'),
        ('t_mg_rich', 'float64')
    ]
)

con.create_table('test_algo_winrate_target', schema=schema, temp=True)
```

{
	"name": "DatabaseError",
	"message": ":HTTPDriver for http://cc-j6c9l15edn66o817k.public.clickhouse.ads.aliyuncs.com:8123 returned response code 400)
 Code: 62. DB::Exception: Syntax error: failed at position 333 (end of query) (line 12, col 12): . Expected one of: token, Arrow, DoubleColon, non-empty parenthesized list of expressions, end of query. (SYNTAX_ERROR) (version 22.8.5.29)
",
	"stack": "---------------------------------------------------------------------------
DatabaseError                             Traceback (most recent call last)
Cell In[4], line 1
----> 1 con.create_table('test_algo_winrate_target', schema=schema, temp=True)

File ~/.pyenv/versions/3.11.7/envs/venv311/lib/python3.11/site-packages/ibis/backends/clickhouse/__init__.py:737, in Backend.create_table(self, name, obj, schema, database, temp, overwrite, engine, order_by, partition_by, sample_by, settings)
    735 # create the table
    736 sql = code.sql(self.name, pretty=True)
--> 737 self.con.raw_query(sql, external_data=external_data)
    739 return self.table(name, database=database)

File ~/.pyenv/versions/3.11.7/envs/venv311/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py:472, in HttpClient.raw_query(self, query, parameters, settings, fmt, use_database, external_data)
    470     body = final_query
    471     fields = None
--> 472 return self._raw_request(body, params, fields=fields).data

File ~/.pyenv/versions/3.11.7/envs/venv311/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py:437, in HttpClient._raw_request(self, data, params, headers, method, retries, stream, server_wait, fields, error_handler)
    435     error_handler(response)
    436 else:
--> 437     self._error_handler(response)

File ~/.pyenv/versions/3.11.7/envs/venv311/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py:361, in HttpClient._error_handler(self, response, retried)
    359     err_msg = common.format_error(err_content.decode(errors='backslashreplace'))
    360     err_str = f':{err_str}\
 {err_msg}'
--> 361 raise OperationalError(err_str) if retried else DatabaseError(err_str) from None

DatabaseError: :HTTPDriver for http://cc-j6c9l15edn66o817k.public.clickhouse.ads.aliyuncs.com:8123 returned response code 400)
 Code: 62. DB::Exception: Syntax error: failed at position 333 (end of query) (line 12, col 12): . Expected one of: token, Arrow, DoubleColon, non-empty parenthesized list of expressions, end of query. (SYNTAX_ERROR) (version 22.8.5.29)
"
}
